export const UNIVERSAL_SCALE = 0.01;

export const EARTH_RADIUS_KM_EQUATOR = 6378.137 * UNIVERSAL_SCALE;
const EARTH_RADIUS_KM_POLES = 6356.752 * UNIVERSAL_SCALE;

export const EARTH_Y_TO_X_SCALE =
  EARTH_RADIUS_KM_POLES / EARTH_RADIUS_KM_EQUATOR;
export const INITIAL_CAMERA_HEIGHT_ABOVE_EARTH_KM = 10000 * UNIVERSAL_SCALE;

export const STARS_DISTANCE =
  EARTH_RADIUS_KM_EQUATOR + 100000 * UNIVERSAL_SCALE;
