import List from "@mui/material/List";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import dynamic from "next/dynamic";
import { ReactElement } from "react";

// async function init() {
//   const rustModule = await import("../wasm/add.wasm");

//   console.log("rustModule", rustModule);
//   const value = rustModule.add_one(14);

//   console.log("value", value);
// }

// const RustComponent = dynamic({
//   loader: async () => {
//     // Import the wasm module
//     const rustModule = await import("../add.wasm");

//     console.log(rustModule);
//     // Return a React component that calls the add_one method on the wasm module
//     return (props) => <div>{rustModule.add_one(props.number)}</div>;
//   },
// });

function Home() {
  //init();
  return (
    <>
      <Head>
        <title>{`Reggie's Next.js Playground`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export default Home;

Home.getLayout = function getLayout(page: ReactElement) {
  return page;
};
