import List from "@mui/material/List";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import dynamic from "next/dynamic";
import { ReactElement } from "react";
import Container from "@mui/material/Container";
import ListItem from "@mui/material/ListItem";
import { CustomLink } from "../Components/CustomLink";
import { HomePageVisualization } from "../Components/HomePageVisualization";
import { Box } from "@mui/material";

// async function init() {
//   const rustModule = await import("../wasm/add.wasm");

//   console.log("rustModule", rustModule);
//   const value = rustModule.add_one(14);

//   console.log("value", value);
// }

// const RustComponent = dynamic({
//   loader: async () => {
//     // Import the wasm module
//     const rustModule = await import("../add.wasm");

//     console.log(rustModule);
//     // Return a React component that calls the add_one method on the wasm module
//     return (props) => <div>{rustModule.add_one(props.number)}</div>;
//   },
// });

function Home() {
  //init();
  return (
    <>
      <Head>
        <title>{`Reggie's Next.js Playground`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <List>
          <ListItem>
            <CustomLink href="/audio-visualizers">Audio Viz</CustomLink>
          </ListItem>
          <ListItem>
            <CustomLink href="/web-audio">Web Audio</CustomLink>
          </ListItem>
          <ListItem>
            <CustomLink href="/globe">3D Globe</CustomLink>
          </ListItem>
        </List>
      </Container>
      <Box sx={{ position: "absolute", top: 0, bottom: 0, right: 0, left: 0 }}>
        <HomePageVisualization />
      </Box>
    </>
  );
}

export default Home;

Home.getLayout = (page: ReactElement) => page;
